### PR TITLE
fix: cpu intensive usage

### PR DESCRIPTION
**Pull request by CRGao**
The current timer will cause high cpu usage

截圖 2022-12-30 下午3 54 04

### CODE REVIEW

**Comment by antoniodipinto** [comment]
@CRGao can you please show the benchmark for the new integration?

**Comment by antoniodipinto** [comment]
Leaving here more details based on Go documentation about time.Tick

> Tick is a convenience wrapper for NewTicker providing access to the ticking channel only. While Tick is useful for clients that have no need to shut down the Ticker, be aware that without a way to shut it down the underlying Ticker cannot be recovered by the garbage collector; it "leaks". Unlike NewTicker, Tick will return nil if d <= 0

Source: https://pkg.go.dev/time?utm_source=godoc#Tick

**Review by antoniodipinto — APPROVED** [review]

**Comment by antoniodipinto** [comment]
Merged.

Thanks @CRGao

**Comment by CRGao** [comment]
> @CRGao你能展示新集成的基準嗎？

截圖 2023-01-02 下午8 50 49

**Pull request merged**
